import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from './utils';
import type { Disbursement, GrantWithRelations } from './types';

interface ExportData {
  grant: GrantWithRelations;
  disbursements: Disbursement[];
  totalDisbursed: number;
  remainingBalance: number;
  exportedBy: string;
}

export function exportDisbursementsToPDF(data: ExportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Disbursement History Report', pageWidth / 2, 20, { align: 'center' });

  // Grant Information
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Grant Information', 14, 35);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Project: ${data.grant.project_name}`, 14, 42);
  doc.text(`Fund Source: ${data.grant.fund_sources?.source_name || 'N/A'}`, 14, 48);
  doc.text(`Year: ${data.grant.grant_years?.year_value || 'N/A'}`, 14, 54);
  doc.text(`Status: ${data.grant.status}`, 14, 60);

  // Summary Section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, 72);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Approved: ${formatCurrency(data.grant.amount_approved)}`, 14, 79);
  doc.text(`Total Disbursed: ${formatCurrency(data.totalDisbursed)}`, 14, 85);
  doc.text(`Remaining Balance: ${formatCurrency(data.remainingBalance)}`, 14, 91);

  // Disbursements Table
  const tableData = data.disbursements.map(d => [
    formatDate(d.payment_date),
    formatCurrency(d.amount)
  ]);

  autoTable(doc, {
    startY: 100,
    head: [['Payment Date', 'Amount']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 58, 138], // blue-900
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10
    },
    bodyStyles: {
      fontSize: 9
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252] // slate-50
    }
  });

  // Footer
  const finalY = (doc as any).lastAutoTable.finalY || 100;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(`Generated on: ${formatDate(new Date().toISOString())}`, 14, finalY + 15);
  doc.text(`Generated by: ${data.exportedBy}`, 14, finalY + 20);

  // Save the PDF
  const fileName = `Disbursements_${data.grant.project_name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}
